import type { AdvisoryAnalysisOutput } from "@/lib/advisory-output-types";

/** PoC sample — schema-compliant `advisory_analysis_output` for TargetCo */
export const SAMPLE_ADVISORY_OUTPUT: AdvisoryAnalysisOutput = {
  engagement: {
    engagement_ref: "TAS-2025-0042",
    client_name: "TargetCo Acquisition",
    deal_type: "Transaction Diligence",
    period_start: "Jan-23",
    period_end: "Jan-26",
    total_months: 37,
    currency: "USD",
    materiality_threshold: 50000,
    anomaly_pct_threshold: 0.15,
    report_generated_at: "2026-05-21T14:30:00Z",
    total_accounts_parsed: 847,
  },
  parse_warnings: [
    {
      warning_type: "inferred_account_type",
      account_code: "4999",
      period: "",
      detail: "Account type inferred from GL range — no explicit type in source file",
    },
  ],
  suppressed_anomalies: [
    {
      account_code: "6100",
      account_name: "Payroll Expense",
      period: "Mar-25",
      flag_type: "SPIKE",
      absolute_delta: 385000,
      suppression_reason: "Three-payroll month per 53-week fiscal calendar (WP-03)",
    },
  ],
  issue_log: [
    {
      issue_id: "ISS-001",
      anomaly_id: "ANM-001",
      display_order: 1,
      account_code: "4100",
      account_name: "Revenue — Product Sales",
      account_type: "Revenue",
      flag_type: "SPIKE",
      severity: "HIGH",
      direction: "DOWN",
      period_start: "Jan-26",
      period_end: "Jan-26",
      absolute_delta: -700000,
      mom_pct_change: -0.184,
      baseline_avg: 3800000,
      peak_value: 3100000,
      issue_summary: "Product revenue fell 18.4% MoM in Jan-26 with AR decline",
      driver_explanation:
        "Revenue declined $700K month-over-month in Jan-26. AR decreased $2.1M in the same period, suggesting collection acceleration rather than new demand. Top customer concentration: Customer A orders down 34% per shipment log.",
      driver_category: "Collections",
      recurrence_type: "UNKNOWN",
      confidence: "MEDIUM",
      is_unexplained: false,
      needs_immediate_attention: false,
      correlated_accounts: [
        {
          account_code: "1200",
          account_name: "Accounts Receivable",
          correlation_direction: "INVERSE",
          correlation_note: "AR fell while revenue fell — inconsistent with typical collection lag pattern",
        },
      ],
      follow_up_questions: [
        {
          question_id: "Q-001",
          question_text:
            "What specific customer contracts or product lines drove the 18.4% MoM revenue decline in Jan-26 for account 4100 ($3.1M)?",
          priority: 1,
          category: "Revenue",
          question_type: "Investigative",
          requires_documentation: true,
          context_note: "Correlate with Customer A shipment log",
          agenda_status: "PENDING",
        },
      ],
      workpaper_ref: "WP-07",
      workpaper_excerpt: "Customer A volume down 34% vs prior month per shipment schedule.",
      source_refs: ["TB row 4100 · Jan-26"],
      review_status: "PENDING_REVIEW",
      reviewer_comment: "",
      driver_status: "PENDING",
      tracker_status: "PENDING",
    },
    {
      issue_id: "ISS-002",
      anomaly_id: "ANM-002",
      display_order: 2,
      account_code: "6100",
      account_name: "Payroll Expense",
      account_type: "OpEx",
      flag_type: "SPIKE",
      severity: "HIGH",
      direction: "UP",
      period_start: "Mar-25",
      period_end: "Mar-25",
      absolute_delta: 385000,
      mom_pct_change: 0.42,
      baseline_avg: 915000,
      peak_value: 1300000,
      issue_summary: "Payroll spike +42% in Mar-25 — calendar vs bonus accrual",
      driver_explanation:
        "March 2025 payroll increased 42% vs trailing six-month average. Primary driver is three-payroll month under 53-week fiscal calendar; secondary $180K bonus accrual true-up and 12 FTE adds in Feb-25.",
      driver_category: "Calendar",
      recurrence_type: "ONE_TIME",
      confidence: "HIGH",
      is_unexplained: false,
      needs_immediate_attention: false,
      correlated_accounts: [
        {
          account_code: "2150",
          account_name: "Accrued Payroll",
          correlation_direction: "SAME",
          correlation_note: "Accrued payroll moved in line with gross payroll spike",
        },
      ],
      follow_up_questions: [
        {
          question_id: "Q-002",
          question_text:
            "Please confirm three-payroll month treatment for Mar-25 payroll ($1.31M) and whether the $180K bonus accrual true-up is non-recurring.",
          priority: 1,
          category: "Payroll",
          question_type: "Confirmation",
          requires_documentation: true,
          context_note: "Suppressed in anomaly list — surfaced as issue for management Q",
          agenda_status: "PENDING",
        },
      ],
      workpaper_ref: "WP-03",
      workpaper_excerpt: "53-week calendar — three payroll runs in March 2025.",
      source_refs: ["TB row 6100 · Mar-25"],
      review_status: "PENDING_REVIEW",
      reviewer_comment: "",
      driver_status: "PENDING",
      tracker_status: "PENDING",
    },
    {
      issue_id: "ISS-003",
      anomaly_id: "ANM-003",
      display_order: 3,
      account_code: "1200",
      account_name: "Accounts Receivable",
      account_type: "Asset",
      flag_type: "TREND",
      severity: "HIGH",
      direction: "UP",
      period_start: "Oct-25",
      period_end: "Dec-25",
      absolute_delta: 600000,
      mom_pct_change: 0.283,
      baseline_avg: 2100000,
      peak_value: 2600000,
      issue_summary: "DSO expanded to 68 days by Dec-25 — Customer B terms",
      driver_explanation:
        "AR balance grew through Q4 2025 with DSO expanding from 52 to 68 days. Customer B payment terms extended 30→60 days in Nov-25. Revenue recognition timing mismatch with collections noted in workpapers.",
      driver_category: "Collections",
      recurrence_type: "RECURRING",
      confidence: "HIGH",
      is_unexplained: false,
      needs_immediate_attention: false,
      correlated_accounts: [
        {
          account_code: "4100",
          account_name: "Revenue — Product Sales",
          correlation_direction: "INVERSE",
          correlation_note: "Revenue softened in Q4 while AR grew — working capital strain signal",
        },
      ],
      follow_up_questions: [
        {
          question_id: "Q-003",
          question_text:
            "What is management's plan to address Customer B's extended payment terms and any covenant implications from DSO at 68 days?",
          priority: 2,
          category: "Working_Capital",
          question_type: "Investigative",
          requires_documentation: false,
          context_note: "",
          agenda_status: "PENDING",
        },
      ],
      workpaper_ref: "WP-12",
      workpaper_excerpt: "Customer B terms 30→60 days effective Nov 2025.",
      source_refs: ["TB row 1200 · Dec-25"],
      review_status: "PENDING_REVIEW",
      reviewer_comment: "",
      driver_status: "PENDING",
      tracker_status: "PENDING",
    },
    {
      issue_id: "ISS-004",
      anomaly_id: "ANM-004",
      display_order: 4,
      account_code: "GM",
      account_name: "Gross Margin %",
      account_type: "Other",
      flag_type: "MARGIN_COMPRESSION",
      severity: "MEDIUM",
      direction: "DOWN",
      period_start: "Jan-25",
      period_end: "Dec-25",
      absolute_delta: -0.032,
      mom_pct_change: -0.08,
      baseline_avg: 0.42,
      peak_value: 0.388,
      issue_summary: "Gross margin compressed 3.2 pts in FY-25",
      driver_explanation:
        "COGS growth (+12%) outpaced revenue growth (+6%) in FY-25. Raw materials cost pass-through to customers incomplete per management commentary.",
      driver_category: "Cost_Inflation",
      recurrence_type: "RECURRING",
      confidence: "MEDIUM",
      is_unexplained: false,
      needs_immediate_attention: false,
      correlated_accounts: [
        {
          account_code: "5100",
          account_name: "COGS",
          correlation_direction: "SAME",
          correlation_note: "COGS trend explains majority of margin compression",
        },
      ],
      follow_up_questions: [
        {
          question_id: "Q-004",
          question_text:
            "What percentage of raw material cost increases have been passed through to customers in the last 12 months?",
          priority: 3,
          category: "Cost",
          question_type: "Run_Rate",
          requires_documentation: false,
          context_note: "",
          agenda_status: "PENDING",
        },
      ],
      workpaper_ref: "",
      workpaper_excerpt: "",
      source_refs: ["Derived · FY-25"],
      review_status: "PENDING_REVIEW",
      reviewer_comment: "",
      driver_status: "PENDING",
      tracker_status: "PENDING",
    },
    {
      issue_id: "ISS-005",
      anomaly_id: "ANM-005",
      display_order: 5,
      account_code: "6300",
      account_name: "SG&A — Professional Fees",
      account_type: "OpEx",
      flag_type: "SPIKE",
      severity: "LOW",
      direction: "UP",
      period_start: "Nov-25",
      period_end: "Nov-25",
      absolute_delta: 245000,
      mom_pct_change: 1.56,
      baseline_avg: 157000,
      peak_value: 402000,
      issue_summary: "One-time legal advisory fees in Nov-25",
      driver_explanation:
        "Non-recurring M&A transaction legal costs per workpaper note 4.2 — excluded from normalized EBITDA bridge.",
      driver_category: "Legal",
      recurrence_type: "ONE_TIME",
      confidence: "HIGH",
      is_unexplained: false,
      needs_immediate_attention: false,
      correlated_accounts: [],
      follow_up_questions: [
        {
          question_id: "Q-005",
          question_text:
            "Confirm SG&A legal fees ($402K, Nov-25, account 6300) are excluded from normalized EBITDA per management bridge.",
          priority: 4,
          category: "Legal",
          question_type: "Confirmation",
          requires_documentation: true,
          context_note: "",
          agenda_status: "PENDING",
        },
      ],
      workpaper_ref: "WP-04",
      workpaper_excerpt: "M&A legal fees — one-time, excluded from normalized EBITDA.",
      source_refs: ["TB row 6300 · Nov-25"],
      review_status: "APPROVED",
      reviewer_comment: "",
      driver_status: "PENDING",
      tracker_status: "PENDING",
    },
  ],
  report: {
    executive_summary:
      "Transaction diligence over 37 months identifies 5 material issues: 2 HIGH severity (revenue decline, AR/DSO), 1 MEDIUM (margin compression), and 1 LOW (legal fees). Revenue softness in Jan-26 correlates with working capital trends. Payroll spike in Mar-25 is calendar-driven. Four findings await advisory review before client delivery.",
    issue_table: [
      {
        issue_number: "ISS-001",
        account: "4100 Revenue — Product Sales",
        period: "Jan-26",
        movement: "Down $700,000 (18.4%) in Jan-26",
        driver: "Collections",
        severity: "HIGH",
        primary_question:
          "What specific customer contracts or product lines drove the 18.4% MoM revenue decline in Jan-26 for account 4100 ($3.1M)?",
      },
      {
        issue_number: "ISS-002",
        account: "6100 Payroll Expense",
        period: "Mar-25",
        movement: "Up $385,000 (42.0%) in Mar-25",
        driver: "Calendar",
        severity: "HIGH",
        primary_question:
          "Please confirm three-payroll month treatment for Mar-25 payroll ($1.31M) and whether the $180K bonus accrual true-up is non-recurring.",
      },
      {
        issue_number: "ISS-003",
        account: "1200 Accounts Receivable",
        period: "Oct-25 to Dec-25",
        movement: "Up $600,000 (28.3%) — DSO 68 days",
        driver: "Collections",
        severity: "HIGH",
        primary_question:
          "What is management's plan to address Customer B's extended payment terms and any covenant implications from DSO at 68 days?",
      },
      {
        issue_number: "ISS-004",
        account: "Gross Margin %",
        period: "Jan-25 to Dec-25",
        movement: "Down 3.2 pts in FY-25",
        driver: "Cost_Inflation",
        severity: "MEDIUM",
        primary_question:
          "What percentage of raw material cost increases have been passed through to customers in the last 12 months?",
      },
      {
        issue_number: "ISS-005",
        account: "6300 SG&A — Professional Fees",
        period: "Nov-25",
        movement: "Up $245,000 (156%) in Nov-25",
        driver: "Legal",
        severity: "LOW",
        primary_question:
          "Confirm SG&A legal fees ($402K, Nov-25, account 6300) are excluded from normalized EBITDA per management bridge.",
      },
    ],
    findings_detail: [
      {
        issue_id: "ISS-001",
        observation: "Revenue — Product Sales (4100) declined 18.4% MoM to $3.1M in Jan-26.",
        driver:
          "Revenue declined $700K month-over-month in Jan-26. AR decreased $2.1M in the same period, suggesting collection acceleration rather than new demand.",
        implications: "If demand-driven, run-rate revenue and EBITDA may require downward adjustment for diligence.",
        follow_up_questions: [
          "What specific customer contracts or product lines drove the 18.4% MoM revenue decline in Jan-26 for account 4100 ($3.1M)?",
        ],
        source_refs: ["TB row 4100 · Jan-26", "WP-07"],
      },
      {
        issue_id: "ISS-002",
        observation: "Payroll Expense (6100) spiked 42% to $1.31M in Mar-25.",
        driver:
          "March 2025 payroll increased 42% vs trailing six-month average. Primary driver is three-payroll month under 53-week fiscal calendar.",
        implications: "Normalized payroll run-rate estimated at ~$920K/month post-adjustment.",
        follow_up_questions: [
          "Please confirm three-payroll month treatment for Mar-25 payroll ($1.31M) and whether the $180K bonus accrual true-up is non-recurring.",
        ],
        source_refs: ["TB row 6100 · Mar-25", "WP-03"],
      },
      {
        issue_id: "ISS-003",
        observation: "AR (1200) trend elevated DSO to 68 days by Dec-25.",
        driver:
          "Customer B payment terms extended 30→60 days in Nov-25. Revenue recognition timing mismatch with collections.",
        implications: "Working capital peg and cash conversion cycle may worsen without remediation.",
        follow_up_questions: [
          "What is management's plan to address Customer B's extended payment terms and any covenant implications from DSO at 68 days?",
        ],
        source_refs: ["TB row 1200 · Dec-25", "WP-12"],
      },
      {
        issue_id: "ISS-004",
        observation: "Gross margin compressed 3.2 percentage points in FY-25.",
        driver: "COGS growth (+12%) outpaced revenue growth (+6%). Incomplete cost pass-through.",
        implications: "Forward margin assumptions should reflect inflation lag unless pricing actions documented.",
        follow_up_questions: [
          "What percentage of raw material cost increases have been passed through to customers in the last 12 months?",
        ],
        source_refs: ["Derived · FY-25"],
      },
      {
        issue_id: "ISS-005",
        observation: "SG&A Professional Fees (6300) +156% in Nov-25 to $402K.",
        driver: "Non-recurring M&A transaction legal costs per workpaper note 4.2.",
        implications: "Excluded from normalized EBITDA — confirm in management bridge.",
        follow_up_questions: [
          "Confirm SG&A legal fees ($402K, Nov-25, account 6300) are excluded from normalized EBITDA per management bridge.",
        ],
        source_refs: ["TB row 6300 · Nov-25", "WP-04"],
      },
    ],
    question_agenda: {
      Revenue: [
        "What specific customer contracts or product lines drove the 18.4% MoM revenue decline in Jan-26 for account 4100 ($3.1M)?",
      ],
      Cost: [
        "What percentage of raw material cost increases have been passed through to customers in the last 12 months?",
      ],
      Working_Capital: [
        "What is management's plan to address Customer B's extended payment terms and any covenant implications from DSO at 68 days?",
      ],
      Payroll: [
        "Please confirm three-payroll month treatment for Mar-25 payroll ($1.31M) and whether the $180K bonus accrual true-up is non-recurring.",
      ],
      Legal: [
        "Confirm SG&A legal fees ($402K, Nov-25, account 6300) are excluded from normalized EBITDA per management bridge.",
      ],
      Other: [],
    },
    workpaper_index: [
      { ref: "WP-03", account: "6100 Payroll", period: "Mar-25", note_type: "Calendar adjustment" },
      { ref: "WP-04", account: "6300 SG&A", period: "Nov-25", note_type: "M&A legal — one-time" },
      { ref: "WP-07", account: "4100 Revenue", period: "Jan-26", note_type: "Customer concentration" },
      { ref: "WP-12", account: "1200 AR", period: "Dec-25", note_type: "Payment terms" },
    ],
  },
  summary_stats: {
    total_issues: 5,
    high_severity: 3,
    medium_severity: 1,
    low_severity: 1,
    needs_immediate_attention: 0,
    unexplained: 0,
    total_questions: 5,
    suppressed_anomalies: 1,
    workpaper_notes_matched: 4,
    parse_warnings: 1,
  },
};
